In [1]:
import glob
import numpy as np
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt


## Загружаем боксы

In [2]:
filelist = glob.glob('images/*.png')
data = [[np.array(Image.open(fname).resize((28, 28)).convert('L')).ravel(), int(fname.split('/')[1].split('.')[0])] for fname in filelist]

# labels = np.array(int(fname.split('/')[1].split('.')[0]) for fname in filelist)


## Ресайз изображений

In [37]:
# new_size = ()

# data[0][0]

In [54]:
pd_data = pd.DataFrame(data, columns=['image', 'label'])
pd_data.rename(columns={"label": "boxid"}, inplace=True)
pd_data = pd_data.astype({'boxid': 'int64'})

In [55]:
# pd_data

In [56]:
target = pd.read_csv('./images_labelling.csv')
target = target.astype({'boxid': 'int64'})

## Мержим колонки

In [57]:
all_data = pd.merge(pd_data, target, on='boxid', how='inner')

In [58]:
# all_data

In [59]:
# train_images = np.array(all_data['image'])
train_images =np.reshape(np.array(list(map(lambda img: np.reshape(img, (1, 784)), all_data['image']))), (3750,784))
train_target = np.array(all_data['label'])

In [60]:
# new_data = np.array(list(map(lambda img: np.reshape(img, (1, 784)), all_data['image'])))
# final = 
# final.shape

### Изучаем данные

In [61]:
# all_data['label'].value_counts()

## Препроцессинг

In [62]:
X_train, X_test, y_train, y_test = train_test_split(train_images, train_target, test_size=0.2, random_state=42)
y_train = np.reshape(y_train.astype(int), (3000, 1))
y_test = np.reshape(y_test.astype(int), (750, 1))
batch_size =len(X_train)

print(X_train.shape, y_train.shape, y_test.shape )

(3000, 784) (3000, 1) (750, 1)


In [63]:
# print(f'type={type(X_train)}')
# print(f'shape={X_train.shape}')
# X_train_reshaped = np.reshape(X_train, (3000, 784))

In [64]:
scaler = MinMaxScaler()
# Train
X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))
# test
X_test_scaled = scaler.fit_transform(X_test.astype(np.float64))
feature_columns = [tf.feature_column.numeric_column('x', shape=X_train_scaled.shape[1:])]
X_train_scaled.shape[1:]

(784,)

## Строим CNN

In [66]:
def cnn_model_fn(features, labels, mode):
  """Model function for CNN."""
  # Input Layer
  input_layer = tf.reshape(features["x"], [-1, 28, 28, 1])

  # Convolutional Layer
  conv1 = tf.layers.conv2d(
      inputs=input_layer,
      filters=32,
      kernel_size=[5, 5],
      padding="same",
      activation=tf.nn.relu)

  # Pooling Layer
  pool1 = tf.layers.max_pooling2d(inputs=conv1, pool_size=[2, 2], strides=2)

  # Convolutional Layer #2 and Pooling Layer
  conv2 = tf.layers.conv2d(
      inputs=pool1,
      filters=36,
      kernel_size=[5, 5],
      padding="same",
      activation=tf.nn.relu)
  pool2 = tf.layers.max_pooling2d(inputs=conv2, pool_size=[2, 2], strides=2)

  # Dense Layer
  pool2_flat = tf.reshape(pool2, [-1, 7 * 7 * 36])
  dense = tf.layers.dense(inputs=pool2_flat, units=7 * 7 * 36, activation=tf.nn.relu)
  dropout = tf.layers.dropout(
      inputs=dense, rate=0.4, training=mode == tf.estimator.ModeKeys.TRAIN)

  # Logits Layer
  logits = tf.layers.dense(inputs=dropout, units=25)
  print(logits)

  predictions = {
      # Generate predictions (for PREDICT and EVAL mode)
      "classes": tf.argmax(input=logits, axis=1),
      "probabilities": tf.nn.softmax(logits, name="softmax_tensor")
  }

  if mode == tf.estimator.ModeKeys.PREDICT:
    return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions)

  # Calculate Loss
  loss = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits)

  # Configure the Training Op (for TRAIN mode)
  if mode == tf.estimator.ModeKeys.TRAIN:
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
    train_op = optimizer.minimize(
        loss=loss,
        global_step=tf.train.get_global_step())
    return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)

  # Add evaluation metrics Evaluation mode
  eval_metric_ops = {
      "accuracy": tf.metrics.accuracy(
          labels=labels, predictions=predictions["classes"])}
  return tf.estimator.EstimatorSpec(
      mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)

In [67]:
mnist_classifier = tf.estimator.Estimator(
    model_fn=cnn_model_fn, model_dir="train/mnist_convnet_model")

tensors_to_log = {"probabilities": "softmax_tensor"}
logging_hook = tf.train.LoggingTensorHook(tensors=tensors_to_log, every_n_iter=50)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'train/mnist_convnet_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x111d127b8>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [68]:
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": X_train_scaled},
    y=y_train,
    batch_size=100,
    num_epochs=None,
    shuffle=True)

mnist_classifier.train(
    input_fn=train_input_fn,
    steps=16000,
    hooks=[logging_hook]
)



INFO:tensorflow:Calling model_fn.
Tensor("dense_1/BiasAdd:0", shape=(100, 25), dtype=float64)
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into train/mnist_convnet_model/model.ckpt.
INFO:tensorflow:probabilities = [[0.03853391 0.03712416 0.03950143 ... 0.03730933 0.03552312 0.03916558]
 [0.04082821 0.03778776 0.04252597 ... 0.0385475  0.03511583 0.03839587]
 [0.03389361 0.03710553 0.04380228 ... 0.03740202 0.03668085 0.0391405 ]
 ...
 [0.03547625 0.0338894  0.04003988 ... 0.03682766 0.03694133 0.04091042]
 [0.03861617 0.03714374 0.04370834 ... 0.03782767 0.03437984 0.03758212]
 [0.03693434 0.03679974 0.0420957  ... 0.03814252 0.0389725  0.04026057]]
INFO:tensorflow:loss = 3.217526435852051, step = 1
INFO:tensorflow:probabilities = [[0.03637209 0.03671942 0.04143915 ... 0.03981236 0.0351326 

INFO:tensorflow:loss = 3.205230951309204, step = 701 (40.309 sec)
INFO:tensorflow:probabilities = [[0.03454822 0.03293593 0.04060187 ... 0.03387356 0.03884541 0.03619389]
 [0.04100433 0.0371633  0.04391724 ... 0.03730843 0.03715859 0.03579431]
 [0.03579085 0.03631664 0.04352158 ... 0.03989073 0.03911017 0.03914284]
 ...
 [0.03774698 0.03609574 0.04124442 ... 0.03945389 0.04013838 0.03615463]
 [0.03451573 0.03091001 0.04079397 ... 0.03156475 0.03533281 0.03409274]
 [0.03392621 0.03648674 0.04243562 ... 0.03875679 0.03970052 0.03673668]] (18.905 sec)
INFO:tensorflow:global_step/sec: 2.72449
INFO:tensorflow:probabilities = [[0.03481456 0.03752529 0.04550151 ... 0.03680553 0.04198212 0.03255238]
 [0.03790163 0.03891167 0.03905986 ... 0.03815066 0.04181281 0.03643977]
 [0.03088752 0.03478999 0.04146829 ... 0.04182797 0.03817081 0.03694855]
 ...
 [0.03629171 0.03506671 0.03879633 ... 0.03498826 0.03716233 0.03677394]
 [0.03153031 0.03388199 0.04173164 ... 0.03645963 0.03865223 0.0391119 ]
 [

INFO:tensorflow:global_step/sec: 0.339614
INFO:tensorflow:probabilities = [[0.03732572 0.03867621 0.03603853 ... 0.03364133 0.03869157 0.03519404]
 [0.04045876 0.03758509 0.04443402 ... 0.03867532 0.0376416  0.03257827]
 [0.03380484 0.03501603 0.03668423 ... 0.03598755 0.04243027 0.03465795]
 ...
 [0.03054404 0.03189051 0.03602425 ... 0.03361608 0.03572758 0.03425771]
 [0.03487813 0.03432475 0.03816988 ... 0.03577021 0.0416926  0.03109487]
 [0.03635704 0.03503158 0.03743944 ... 0.034151   0.03883667 0.03277562]] (277.224 sec)
INFO:tensorflow:loss = 3.1932311058044434, step = 1501 (294.453 sec)
INFO:tensorflow:probabilities = [[0.03732478 0.03556162 0.04237778 ... 0.03560045 0.04724096 0.03122471]
 [0.02899313 0.03007712 0.03737199 ... 0.03911966 0.03691237 0.03584888]
 [0.03216518 0.03447628 0.0346278  ... 0.04070286 0.03459276 0.03411316]
 ...
 [0.03015494 0.03668085 0.03896042 ... 0.04174599 0.03459958 0.03420518]
 [0.0361891  0.03740408 0.03954095 ... 0.04379277 0.04001156 0.0363911

INFO:tensorflow:probabilities = [[0.02670544 0.03251035 0.03029722 ... 0.03095107 0.0343889  0.02158109]
 [0.03381642 0.03757745 0.03512627 ... 0.03296853 0.04603714 0.02947698]
 [0.0293055  0.03711597 0.03623374 ... 0.03154702 0.0438062  0.03959778]
 ...
 [0.03284009 0.03270337 0.04009818 ... 0.0448848  0.04068853 0.03961498]
 [0.03855979 0.03492868 0.03349884 ... 0.03848315 0.04025429 0.03374289]
 [0.02778929 0.02862322 0.02762522 ... 0.02739517 0.03962324 0.03104968]] (25.881 sec)
INFO:tensorflow:global_step/sec: 2.21006
INFO:tensorflow:probabilities = [[0.03074093 0.03363562 0.03493077 ... 0.0394365  0.03160362 0.03007586]
 [0.03753395 0.03934466 0.03530918 ... 0.03244227 0.03859178 0.03091271]
 [0.03302689 0.0327233  0.03707586 ... 0.02807496 0.03465854 0.03552732]
 ...
 [0.04511502 0.03582413 0.0386867  ... 0.0419114  0.04131198 0.03458213]
 [0.03064041 0.02596272 0.03008083 ... 0.03345397 0.03617691 0.02888777]
 [0.02266315 0.02369951 0.02734642 ... 0.03025005 0.03318877 0.03649

INFO:tensorflow:probabilities = [[0.01975885 0.02706492 0.02282935 ... 0.02681917 0.02285328 0.02726192]
 [0.01471474 0.02543039 0.03356602 ... 0.02503953 0.03139249 0.01808412]
 [0.03805463 0.02782231 0.04095538 ... 0.04292066 0.03946265 0.03468961]
 ...
 [0.04491468 0.05766796 0.04591552 ... 0.05705638 0.04530422 0.03427761]
 [0.0540642  0.04630793 0.03072259 ... 0.03737244 0.06848454 0.02627416]
 [0.01184649 0.02206778 0.02306113 ... 0.02962301 0.0284363  0.02802731]] (17.622 sec)
INFO:tensorflow:loss = 3.045746088027954, step = 3001 (35.636 sec)
INFO:tensorflow:probabilities = [[0.03830121 0.04417176 0.03095629 ... 0.03075829 0.04857421 0.03726528]
 [0.01965935 0.02243296 0.02746479 ... 0.02408177 0.03219055 0.02325357]
 [0.04095229 0.05295722 0.04483487 ... 0.03365297 0.03676792 0.03045212]
 ...
 [0.03795653 0.02614103 0.04282605 ... 0.03718887 0.04199102 0.02629757]
 [0.01456159 0.02673334 0.02371363 ... 0.01474991 0.02130307 0.0200155 ]
 [0.0400215  0.04317265 0.02912164 ... 0.0

INFO:tensorflow:global_step/sec: 2.83546
INFO:tensorflow:probabilities = [[0.01632075 0.02221915 0.02787261 ... 0.01930332 0.01777949 0.01467946]
 [0.0812376  0.04489775 0.06651036 ... 0.04563042 0.03267724 0.03583981]
 [0.0652566  0.04707188 0.04212398 ... 0.09713201 0.0533521  0.03372397]
 ...
 [0.00781974 0.00977535 0.01217461 ... 0.0169143  0.00739955 0.02016983]
 [0.03130663 0.01949668 0.03154588 ... 0.02795556 0.03027122 0.01686708]
 [0.00664394 0.01032946 0.01538068 ... 0.01986928 0.0179862  0.02674269]] (17.720 sec)
INFO:tensorflow:loss = 2.810941457748413, step = 3801 (35.270 sec)
INFO:tensorflow:probabilities = [[0.05500123 0.06216556 0.05597624 ... 0.0475064  0.04269646 0.04200334]
 [0.00892794 0.00788748 0.01648137 ... 0.01189978 0.01056908 0.01918328]
 [0.0280071  0.0332657  0.0423976  ... 0.04453935 0.07501184 0.02109276]
 ...
 [0.05322121 0.03705301 0.04879411 ... 0.07361542 0.05801371 0.03996621]
 [0.0059102  0.01390249 0.0099327  ... 0.01207601 0.01245724 0.02504717]
 

INFO:tensorflow:loss = 2.623837947845459, step = 4501 (36.353 sec)
INFO:tensorflow:probabilities = [[0.02054407 0.02397977 0.03918098 ... 0.02683946 0.00684068 0.03853226]
 [0.0916344  0.04206454 0.05363464 ... 0.07866883 0.05320933 0.04166808]
 [0.00295384 0.00553271 0.00674378 ... 0.00799108 0.01229881 0.00793981]
 ...
 [0.02601093 0.04135346 0.05761343 ... 0.05209512 0.05228135 0.0972737 ]
 [0.0307638  0.10206734 0.06104356 ... 0.07932062 0.05202118 0.03345343]
 [0.00077607 0.00171758 0.00315385 ... 0.00180251 0.00164019 0.01212539]] (17.720 sec)
INFO:tensorflow:global_step/sec: 2.80158
INFO:tensorflow:probabilities = [[0.03037221 0.09542004 0.03319072 ... 0.02790075 0.05751703 0.09729269]
 [0.10510946 0.07634115 0.05259897 ... 0.04530087 0.04725463 0.03598765]
 [0.00161301 0.00433612 0.01002641 ... 0.00386865 0.00565749 0.01234416]
 ...
 [0.00128867 0.00505201 0.00563626 ... 0.00482275 0.00602785 0.01162928]
 [0.08260591 0.04644203 0.05701121 ... 0.08884583 0.04619356 0.05827502]
 

INFO:tensorflow:probabilities = [[0.07326728 0.04214571 0.03215485 ... 0.06107228 0.07492613 0.05740029]
 [0.00020103 0.00246194 0.00484522 ... 0.00317756 0.00036396 0.00240806]
 [0.0543391  0.06914243 0.05680132 ... 0.1012742  0.08269137 0.02097039]
 ...
 [0.05198156 0.02395098 0.04242424 ... 0.09290498 0.04220268 0.08624167]
 [0.09267621 0.04943712 0.11581909 ... 0.08223118 0.03861464 0.08248669]
 [0.00720532 0.01523088 0.00594377 ... 0.00561575 0.70315804 0.00092028]] (17.733 sec)
INFO:tensorflow:loss = 2.3323276042938232, step = 5301 (35.780 sec)
INFO:tensorflow:probabilities = [[0.00006481 0.00037315 0.00033953 ... 0.00055569 0.00052935 0.00324601]
 [0.00012215 0.0005061  0.0027929  ... 0.00149386 0.00064894 0.00549234]
 [0.08544763 0.05741274 0.08934232 ... 0.09446403 0.02888074 0.03946024]
 ...
 [0.00024749 0.0026011  0.0012557  ... 0.00423875 0.00152057 0.00950909]
 [0.03293348 0.03632268 0.04743739 ... 0.03535698 0.23545127 0.01287805]
 [0.09092373 0.04436843 0.0833894  ... 0.

INFO:tensorflow:probabilities = [[0.1754612  0.06380686 0.06621691 ... 0.0702938  0.04776806 0.05192056]
 [0.00230042 0.0070305  0.01465146 ... 0.00379977 0.00140243 0.14988185]
 [0.00002268 0.00018858 0.00038944 ... 0.00118573 0.00017303 0.00530315]
 ...
 [0.05369143 0.06513656 0.11844973 ... 0.12181559 0.06034398 0.05762609]
 [0.00027572 0.00238057 0.00184543 ... 0.00218388 0.00069439 0.01349937]
 [0.03669713 0.10592553 0.10144335 ... 0.0783195  0.04146974 0.04886894]] (17.423 sec)
INFO:tensorflow:global_step/sec: 2.85362
INFO:tensorflow:probabilities = [[0.06233151 0.04167865 0.13594578 ... 0.05879006 0.12088585 0.01648399]
 [0.00011664 0.00205111 0.00119767 ... 0.00096922 0.00127649 0.01398759]
 [0.00400342 0.025529   0.01055147 ... 0.0107572  0.03317081 0.02274059]
 ...
 [0.01626648 0.00174129 0.00212226 ... 0.00091364 0.00457865 0.00013691]
 [0.13453686 0.09285991 0.0522326  ... 0.0782143  0.03846436 0.04282447]
 [0.00002931 0.00039273 0.00182231 ... 0.00089133 0.00018266 0.01150

INFO:tensorflow:loss = 2.1760339736938477, step = 6801 (39.709 sec)
INFO:tensorflow:probabilities = [[0.16394367 0.0608336  0.13085961 ... 0.08404688 0.05628107 0.00906264]
 [0.0662351  0.06707981 0.06706308 ... 0.1070598  0.06350769 0.03485182]
 [0.00002476 0.00071842 0.00016676 ... 0.00040505 0.00019317 0.00407022]
 ...
 [0.00047387 0.00375553 0.00320074 ... 0.00520905 0.00205879 0.02777398]
 [0.07680249 0.11426498 0.08014179 ... 0.08479003 0.0483766  0.05130152]
 [0.07723684 0.06604173 0.07638246 ... 0.08276589 0.06137426 0.03911648]] (19.503 sec)
INFO:tensorflow:global_step/sec: 2.53604
INFO:tensorflow:probabilities = [[0.04246215 0.06940868 0.08096159 ... 0.10027795 0.04235088 0.04260378]
 [0.0144922  0.00918818 0.0092985  ... 0.00921979 0.39080524 0.01770158]
 [0.07906157 0.0826903  0.04077181 ... 0.08933835 0.02523567 0.0441666 ]
 ...
 [0.10338352 0.04041482 0.06712094 ... 0.08411482 0.01657354 0.06368415]
 [0.00128269 0.00292642 0.00299303 ... 0.00480916 0.00265423 0.07550339]


INFO:tensorflow:global_step/sec: 2.72415
INFO:tensorflow:probabilities = [[0.04692997 0.05564261 0.04426226 ... 0.0976154  0.11232716 0.05154673]
 [0.00009885 0.00416362 0.00082713 ... 0.00108182 0.00296887 0.01476328]
 [0.1112403  0.06467347 0.06080552 ... 0.03995306 0.09573758 0.01010599]
 ...
 [0.00000427 0.00039326 0.0000566  ... 0.00007122 0.00030153 0.00445114]
 [0.14323121 0.0405013  0.04905331 ... 0.07298403 0.06870575 0.01899758]
 [0.00002287 0.00131369 0.00014526 ... 0.00021397 0.00114529 0.00952844]] (18.422 sec)
INFO:tensorflow:loss = 2.1989078521728516, step = 7601 (36.709 sec)
INFO:tensorflow:probabilities = [[0.12158027 0.03944243 0.10021351 ... 0.0722323  0.02637733 0.01882499]
 [0.00000076 0.00014421 0.00008074 ... 0.00004559 0.000052   0.0038917 ]
 [0.03791167 0.09254832 0.04475234 ... 0.10505502 0.12666867 0.02395771]
 ...
 [0.09201461 0.07177113 0.032617   ... 0.05163561 0.12069288 0.02829646]
 [0.00000674 0.00012927 0.00005873 ... 0.00008962 0.00004782 0.00597964]


INFO:tensorflow:probabilities = [[0.00009007 0.00408748 0.00091741 ... 0.0004623  0.00356283 0.01693195]
 [0.02628927 0.12575253 0.13133728 ... 0.14982864 0.02330498 0.01393063]
 [0.06215743 0.07617211 0.05158586 ... 0.17249775 0.03865436 0.02478234]
 ...
 [0.02850511 0.10866297 0.07546388 ... 0.09685821 0.08596704 0.01970675]
 [0.00000084 0.00021005 0.00010217 ... 0.00004967 0.00023459 0.01264091]
 [0.09511354 0.06403192 0.11700271 ... 0.11819954 0.01661922 0.01703595]] (19.092 sec)
INFO:tensorflow:global_step/sec: 2.46147
INFO:tensorflow:probabilities = [[0.00000859 0.00177906 0.0001242  ... 0.00013909 0.00051276 0.01223088]
 [0.00000041 0.00006348 0.0000656  ... 0.00001609 0.00003901 0.00335866]
 [0.00000135 0.00004416 0.00000715 ... 0.00000539 0.00035606 0.00953074]
 ...
 [0.00000028 0.00001578 0.00000793 ... 0.00000263 0.00000598 0.00535218]
 [0.00002831 0.00284469 0.00178676 ... 0.00118814 0.00388094 0.01203679]
 [0.01996924 0.07451279 0.07986317 ... 0.10922794 0.02784631 0.05395

INFO:tensorflow:loss = 1.923556923866272, step = 9101 (38.986 sec)
INFO:tensorflow:Saving checkpoints for 9111 into train/mnist_convnet_model/model.ckpt.
INFO:tensorflow:probabilities = [[0.00000192 0.00032346 0.00004504 ... 0.00004988 0.00007165 0.00439755]
 [0.00011618 0.00052754 0.00313432 ... 0.00259066 0.00837489 0.76638718]
 [0.25054336 0.04500276 0.0447533  ... 0.10012388 0.02253292 0.02063529]
 ...
 [0.00000517 0.00047598 0.00021211 ... 0.00025067 0.00033074 0.00895701]
 [0.00000032 0.00016435 0.00001713 ... 0.00001477 0.00010662 0.00262428]
 [0.00002239 0.00088641 0.00136523 ... 0.00036551 0.00024958 0.003513  ]] (21.864 sec)
INFO:tensorflow:global_step/sec: 2.52758
INFO:tensorflow:probabilities = [[0.00000502 0.0003605  0.00027065 ... 0.00008184 0.00013988 0.00260881]
 [0.0122889  0.05970151 0.0680556  ... 0.01814876 0.11854647 0.02383218]
 [0.11716757 0.07010451 0.04910291 ... 0.09371536 0.03810475 0.00902985]
 ...
 [0.00023065 0.00010526 0.00000608 ... 0.00001852 0.00038705

INFO:tensorflow:global_step/sec: 2.80549
INFO:tensorflow:probabilities = [[0.00001694 0.00036812 0.00063157 ... 0.00043729 0.00025642 0.01670582]
 [0.00000153 0.00021779 0.00010474 ... 0.000035   0.00003032 0.01175102]
 [0.00000931 0.00202385 0.00453336 ... 0.0016721  0.00089853 0.00135038]
 ...
 [0.00000145 0.00015411 0.00005328 ... 0.00002634 0.00012638 0.00393349]
 [0.00000097 0.00009688 0.00010761 ... 0.00001713 0.00001139 0.00018021]
 [0.15401884 0.09897567 0.04761007 ... 0.11907803 0.02196714 0.00678718]] (17.787 sec)
INFO:tensorflow:loss = 1.780598759651184, step = 9901 (35.644 sec)
INFO:tensorflow:probabilities = [[0.01386764 0.02784196 0.00158319 ... 0.00802592 0.07733278 0.67969468]
 [0.00003702 0.00430583 0.00173344 ... 0.00123959 0.00087367 0.01662401]
 [0.00000003 0.00003698 0.00000854 ... 0.00003285 0.0000293  0.00410515]
 ...
 [0.01474414 0.08484489 0.02709031 ... 0.08191586 0.20217277 0.02538749]
 [0.00000238 0.0001211  0.0001692  ... 0.00002394 0.00024437 0.044313  ]
 

INFO:tensorflow:probabilities = [[0.00025017 0.00010741 0.00000216 ... 0.00002095 0.00029821 0.00415268]
 [0.00000014 0.00004397 0.00000823 ... 0.00001045 0.00002531 0.00097772]
 [0.000019   0.00256629 0.1066719  ... 0.02078055 0.00078636 0.21958811]
 ...
 [0.00000023 0.0001121  0.00001184 ... 0.00001277 0.00003285 0.0011026 ]
 [0.0299407  0.04024923 0.16381632 ... 0.11857112 0.03039239 0.01312685]
 [0.2158149  0.0420225  0.0761395  ... 0.03925061 0.01827283 0.02455688]] (19.590 sec)
INFO:tensorflow:global_step/sec: 2.53351
INFO:tensorflow:probabilities = [[0.00001748 0.03260839 0.0000023  ... 0.00000383 0.00000477 0.00010661]
 [0.00000151 0.00092995 0.00012698 ... 0.00006997 0.00073822 0.02117703]
 [0.0770535  0.09641853 0.13748817 ... 0.02818432 0.03991986 0.01252862]
 ...
 [0.07203087 0.01254997 0.00794939 ... 0.00786731 0.05236552 0.00810763]
 [0.00000001 0.00000007 0.00000056 ... 0.00000011 0.00000006 0.99998246]
 [0.0000065  0.00111745 0.00061917 ... 0.00070859 0.00010986 0.01803

INFO:tensorflow:probabilities = [[0.00000005 0.00000794 0.00000093 ... 0.0000147  0.00000666 0.00270057]
 [0.00000019 0.00005595 0.00007716 ... 0.00000978 0.00002312 0.0272153 ]
 [0.00000027 0.00008208 0.00000688 ... 0.00000731 0.00000787 0.01848268]
 ...
 [0.01516121 0.0110047  0.12259645 ... 0.013581   0.06810018 0.10341886]
 [0.02388554 0.00456259 0.00358337 ... 0.00263419 0.02035636 0.56064497]
 [0.08881767 0.1280012  0.05445715 ... 0.15601959 0.02259394 0.01323044]] (17.494 sec)
INFO:tensorflow:loss = 1.7832075357437134, step = 11401 (35.386 sec)
INFO:tensorflow:probabilities = [[0.00000314 0.00068231 0.00013572 ... 0.00030072 0.00022933 0.0080006 ]
 [0.00000862 0.00092833 0.00056826 ... 0.00041703 0.00166583 0.00044607]
 [0.00000002 0.00011411 0.00000246 ... 0.0000037  0.00000919 0.00175153]
 ...
 [0.01354739 0.06219819 0.31209917 ... 0.15585022 0.02556218 0.01057272]
 [0.0071517  0.03147339 0.04596182 ... 0.0407244  0.04807274 0.00150255]
 [0.00000001 0.0000082  0.00000128 ... 0

INFO:tensorflow:global_step/sec: 2.85856
INFO:tensorflow:probabilities = [[0.00035367 0.02861415 0.00416648 ... 0.00496394 0.07178911 0.27065183]
 [0.17486949 0.00240412 0.00106942 ... 0.00064989 0.00642494 0.18366172]
 [0.00754159 0.05780084 0.04712062 ... 0.05560173 0.04615119 0.00985781]
 ...
 [0.02703119 0.03732272 0.0162962  ... 0.06343501 0.07721743 0.00885728]
 [0.00000222 0.00006125 0.00004096 ... 0.00001585 0.00003995 0.00107998]
 [0.00000003 0.00005347 0.00007198 ... 0.00007082 0.00006615 0.00245415]] (17.466 sec)
INFO:tensorflow:loss = 1.742233157157898, step = 12201 (34.982 sec)
INFO:tensorflow:probabilities = [[0.00000174 0.00133302 0.00006411 ... 0.00025309 0.00331406 0.00065532]
 [0.0000515  0.01533742 0.00137934 ... 0.00422869 0.01563019 0.01356567]
 [0.00000002 0.00002101 0.00000121 ... 0.00000096 0.00001151 0.00068275]
 ...
 [0.42057595 0.05381756 0.03373453 ... 0.02720855 0.0263409  0.00634742]
 [0.00000002 0.00004761 0.00000193 ... 0.00000168 0.00005632 0.00040877]


INFO:tensorflow:loss = 1.7309105396270752, step = 12901 (40.898 sec)
INFO:tensorflow:probabilities = [[0.01192826 0.12191973 0.26266995 ... 0.09891174 0.01732    0.00348428]
 [0.02644692 0.12024331 0.19629454 ... 0.19585297 0.03920221 0.00841673]
 [0.00000002 0.00014112 0.000051   ... 0.00000748 0.00005147 0.00217102]
 ...
 [0.00030073 0.19151812 0.21407121 ... 0.06802722 0.17018248 0.04820242]
 [0.         0.00000164 0.00000003 ... 0.00000001 0.00000023 0.00326519]
 [0.11825561 0.05287024 0.00869303 ... 0.00973771 0.00400744 0.00691601]] (20.787 sec)
INFO:tensorflow:global_step/sec: 2.58294
INFO:tensorflow:probabilities = [[0.02017972 0.07248651 0.04776464 ... 0.1875818  0.09951936 0.00675297]
 [0.00000826 0.00006518 0.00005609 ... 0.00035168 0.00497928 0.00124609]
 [0.00000054 0.00042308 0.00001521 ... 0.00003413 0.00024491 0.0006136 ]
 ...
 [0.         0.00003495 0.00001107 ... 0.00000594 0.0000017  0.000246  ]
 [0.00000006 0.00018111 0.00004697 ... 0.00001471 0.00001011 0.00027396]

INFO:tensorflow:probabilities = [[0.         0.00000577 0.00000007 ... 0.00000003 0.00000096 0.00057601]
 [0.03901671 0.13323139 0.13970641 ... 0.10532353 0.09755963 0.01659779]
 [0.         0.00000048 0.00000007 ... 0.         0.0000001  0.00644439]
 ...
 [0.2029978  0.04322541 0.00232562 ... 0.0125418  0.01215448 0.07625914]
 [0.00000081 0.00028807 0.00011441 ... 0.00003783 0.00003892 0.00193048]
 [0.         0.00003337 0.00000337 ... 0.00000083 0.00003742 0.00587021]] (18.259 sec)
INFO:tensorflow:loss = 1.6019256114959717, step = 13701 (38.302 sec)
INFO:tensorflow:probabilities = [[0.04219946 0.02678814 0.09144847 ... 0.14843853 0.04736522 0.10080383]
 [0.03674315 0.20682782 0.27593559 ... 0.09770516 0.04137788 0.00294677]
 [0.         0.00000244 0.00000004 ... 0.00000037 0.00000699 0.00104827]
 ...
 [0.00000001 0.00021376 0.00001177 ... 0.00000504 0.00055205 0.00056881]
 [0.00024655 0.00007775 0.00000296 ... 0.00001085 0.00000633 0.98753991]
 [0.00000002 0.00017653 0.00000293 ... 0

INFO:tensorflow:probabilities = [[0.00066435 0.04661389 0.01127255 ... 0.01982339 0.4850535  0.06564143]
 [0.00000008 0.00007983 0.00001193 ... 0.00000215 0.00003647 0.00095937]
 [0.74128211 0.01504038 0.00859448 ... 0.02735407 0.00135508 0.00304079]
 ...
 [0.0141234  0.0610499  0.00577496 ... 0.06585497 0.05277961 0.01095171]
 [0.03347107 0.04958762 0.01752281 ... 0.11072015 0.05677492 0.00175424]
 [0.         0.00006177 0.00000054 ... 0.00000008 0.00000694 0.00077672]] (24.620 sec)
INFO:tensorflow:global_step/sec: 2.16994
INFO:tensorflow:probabilities = [[0.00000288 0.00000027 0.00000004 ... 0.00000008 0.00000036 0.00007542]
 [0.         0.00000002 0.00000243 ... 0.00000007 0.00000002 0.97465095]
 [0.02963114 0.03929648 0.01313907 ... 0.03795884 0.06631068 0.0058473 ]
 ...
 [0.00000074 0.00069882 0.00011544 ... 0.0000469  0.00013716 0.00103806]
 [0.02027628 0.15402562 0.02607306 ... 0.05376787 0.02636057 0.01090779]
 [0.00000494 0.00037332 0.00008716 ... 0.00003204 0.00004483 0.03461

INFO:tensorflow:loss = 1.6209356784820557, step = 15201 (40.496 sec)
INFO:tensorflow:Saving checkpoints for 15238 into train/mnist_convnet_model/model.ckpt.
INFO:tensorflow:probabilities = [[0.68647823 0.0078064  0.00552417 ... 0.01309097 0.0107357  0.00140431]
 [0.06958229 0.00604915 0.04739431 ... 0.10723188 0.0242083  0.03150499]
 [0.00080493 0.027015   0.01508883 ... 0.04198736 0.64924978 0.01077779]
 ...
 [0.0163278  0.05313492 0.01223625 ... 0.04205022 0.02242153 0.00590859]
 [0.33962074 0.04443847 0.02442482 ... 0.13651248 0.01641894 0.00434821]
 [0.02307002 0.00556975 0.00439569 ... 0.0507242  0.00800814 0.01308307]] (24.565 sec)
INFO:tensorflow:global_step/sec: 2.1508
INFO:tensorflow:probabilities = [[0.00872532 0.03380228 0.14779218 ... 0.18204639 0.03708659 0.00208677]
 [0.04810095 0.13046247 0.03499512 ... 0.01472264 0.06891796 0.0631535 ]
 [0.00000248 0.00075217 0.00004401 ... 0.00005255 0.00005019 0.01772704]
 ...
 [0.06332045 0.05024275 0.03721564 ... 0.02431276 0.067953

INFO:tensorflow:Saving checkpoints for 16000 into train/mnist_convnet_model/model.ckpt.
INFO:tensorflow:Loss for final step: 1.2883155345916748.


In [69]:
eval_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": X_test_scaled},
    y=y_test,
    num_epochs=1,
    shuffle=False)
eval_results = mnist_classifier.evaluate(input_fn=eval_input_fn)
print(eval_results)

INFO:tensorflow:Calling model_fn.
Tensor("dense_1/BiasAdd:0", shape=(?, 25), dtype=float64)
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-11-10T11:53:36Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from train/mnist_convnet_model/model.ckpt-16000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2019-11-10-11:53:37
INFO:tensorflow:Saving dict for global step 16000: accuracy = 0.46266666, global_step = 16000, loss = 1.5904447
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 16000: train/mnist_convnet_model/model.ckpt-16000
{'accuracy': 0.46266666, 'loss': 1.5904447, 'global_step': 16000}
